// Isolated render checks with a minimal document stub. No browser or network access.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map();function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:['[name=project_id]','[name=registration_project]'].includes(selector)?'1':'',scrollLeft:0,scrollTop:0,style:{},classList:{add(){},remove(){}},querySelector(){return node('child')},querySelectorAll(){return[]},addEventListener(){},setAttribute(){},focus(){}});return nodes.get(selector)}
const doc={querySelector:node,querySelectorAll:()=>[],addEventListener(){},activeElement:null,documentElement:{dataset:{},style:{}},body:{classList:{remove(){}}}};
const fixture={user:{id:1,name:'Администратор',role:'admin'},csrf:'test',projects:[{id:1,name:'Тестовый проект',status:'active',city:'Стокгольм',country:'Швеция',timezone:'Europe/Stockholm',start:'2026-01-01',end:'2027-12-31'}],employees:[{id:1,first_name:'Иван',last_name:'Петров',specialty:'Монтажник',status:'active',schedule_version:1}],assignments:[{id:1,employee_id:1,project_id:1,start:'2026-01-01',end:'2027-12-31'}],periods:[],events:[],managers:[],users:[],sites:[],teams:[{id:1,project_id:1,name:'Монтажная команда'}],team_members:[{id:1,project_id:1,employee_id:1,team_id:1,version:1}]};
const context={localStorage:{getItem:()=>null},document:doc,Intl,Date,setTimeout(){},clearTimeout(){},languageSelect:()=>'<select>Language</select>',translateText:x=>x,fixture};vm.createContext(context);
const source=fs.readFileSync('static/app.js','utf8').replace(/^load\(\)\.catch\(.*$/m,'');vm.runInContext(source,context);
vm.runInContext("state=fixture;projectId=1;anchor='2026-10-01';render()",context);
assert.match(node('#content').innerHTML,/Создать учётную запись/);assert.match(node('#calendar').innerHTML,/Монтажная команда/);
vm.runInContext('openEmployee(undefined,1)',context);assert.match(node('#modal-root').innerHTML,/registration_project/);assert.match(node('#registration-assignment').innerHTML,/Начало назначения/);
vm.runInContext('openUser()',context);assert.match(node('#modal-root').innerHTML,/value="secretary"/);
vm.runInContext("state.user.role='secretary';render()",context);
assert.doesNotMatch(node('#content').innerHTML,/Создать учётную запись/);assert.match(node('#content').innerHTML,/data-palette="work"/);assert.match(node('#content').innerHTML,/data-palette="sick"/);assert.doesNotMatch(node('#content').innerHTML,/data-palette="vacation"/);assert.doesNotMatch(node('#app').innerHTML,/data-id="users"/);
vm.runInContext('openTools(1)',context);assert.doesNotMatch(node('#modal-root').innerHTML,/data-act="tool-cycle"/);assert.doesNotMatch(node('#modal-root').innerHTML,/data-act="tool-deactivate"/);
vm.runInContext('openPeriod(1)',context);assert.doesNotMatch(node('#modal-root').innerHTML,/value="vacation"/);assert.match(node('#modal-root').innerHTML,/value="sick"/);
console.log('14 registration, role and team render checks passed');
fixture.teams.push({id:2,project_id:1,name:'Пустая команда',status:'active',version:1});
vm.runInContext("state.user.role='admin';render()",context);
assert.match(node('#calendar').innerHTML,/Пустая команда/);assert.match(node('#calendar').innerHTML,/data-act="team-add" data-id="2"/);assert.match(node('#calendar').innerHTML,/data-act="team-delete" data-id="2"/);
vm.runInContext('openTeam(2)',context);assert.doesNotMatch(node('#modal-root').innerHTML,/<select name="project_id"/);
fixture.periods=[{id:1,project_id:1,employee_id:1,start:'2026-10-01',end:'2026-10-03',kind:'work',layer:0},{id:2,project_id:1,employee_id:1,start:'2026-10-02',end:'2026-10-02',kind:'sick',layer:1}];
assert.equal(vm.runInContext("dailyOnSiteCount('2026-10-01')",context),1);assert.equal(vm.runInContext("dailyOnSiteCount('2026-10-02')",context),0);assert.equal(vm.runInContext("dailyOnSiteCount('2026-10-03')",context),1);
fixture.employees[0].leadership='team_leader';vm.runInContext('render()',context);assert.match(node('#calendar').innerHTML,/leadership-badge tl/);
vm.runInContext("view='projects';render()",context);assert.doesNotMatch(node('#content').innerHTML,/data-act="assign-project"/);
vm.runInContext('toggleTheme()',context);assert.equal(doc.documentElement.dataset.theme,'dark');vm.runInContext('toggleTheme()',context);assert.equal(doc.documentElement.dataset.theme,'light');
console.log('11 empty-team, daily count, badge and theme checks passed');

vm.runInContext("view='employees';render()",context);
assert.match(node('#content').innerHTML,/id="employees-search"/);
assert.equal(vm.runInContext("employeeNameMatches({first_name:'Ąžuolas',last_name:'Žukauskas'},'zuk azu')",context),true);
assert.equal(vm.runInContext("employeeNameMatches({first_name:'Ąžuolas',last_name:'Žukauskas'},'Mantas')",context),false);
vm.runInContext('openTeam(2)',context);assert.match(node('#modal-root').innerHTML,/data-act="delete-current-team">Удалить команду/);
vm.runInContext("view='schedule';render()",context);assert.match(node('#calendar').innerHTML,/class="icon team-delete-button"/);
console.log('Worker name search and visible team deletion checks passed');

fixture.events=[{id:101,project_id:1,employee_id:1,date:'2026-10-02',kind:'outbound',transport:'car',time:'',timezone:'Europe/Vilnius',route:'',flight:''}];
vm.runInContext('render()',context);
assert.match(node('#calendar').innerHTML,/class="rotation travel-day ticket-pending"/);assert.doesNotMatch(node('#calendar').innerHTML,/class="event-pin"/);
assert.match(node('#calendar').innerHTML,/width:24px;top:3px/);
assert.equal(vm.runInContext("dailyOnSiteCount('2026-10-02')",context),0);
assert.deepEqual(JSON.parse(vm.runInContext("JSON.stringify(periodFragments({start:'2026-10-01',end:'2026-10-03'},fixture.events))",context)),[{start:'2026-10-01',end:'2026-10-01'},{start:'2026-10-03',end:'2026-10-03'}]);
vm.runInContext('openEvent(1,fixture.events[0])',context);assert.match(node('#modal-root').innerHTML,/<option value="car" selected>Машина/);
const transportSelect=node('#modal-root').innerHTML.match(/<select name="transport"[^>]*>([\s\S]*?)<\/select>/);
assert.ok(transportSelect);
assert.deepEqual([...transportSelect[1].matchAll(/<option value="([^"]+)"/g)].map(match=>match[1]),['unknown','plane','car','ferry']);
assert.match(node('#modal-root').innerHTML,/<select name="ticket_bought"/);
fixture.events[0].transport='unknown';fixture.events[0].ticket_bought=0;
vm.runInContext('render()',context);
assert.match(node('#calendar').innerHTML,/class="rotation travel-day ticket-pending"/);
assert.match(node('#calendar').innerHTML,/M8 7a4 4 0 0 1 8 0c0 3-4 3-4 7 M12 20h.01/);
assert.match(node('#calendar').innerHTML,/Транспорт не выбран · Билет не куплен/);
assert.match(node('#content').innerHTML,/data-palette="outbound"[^>]*><svg[\s\S]*?M12 2l2 3v5l8 5/);
fixture.events[0].transport='car';fixture.events[0].ticket_bought=1;
vm.runInContext('render()',context);
assert.match(node('#calendar').innerHTML,/class="rotation travel-day ticket-bought"/);
assert.match(node('#calendar').innerHTML,/Машина · Билет куплен/);
vm.runInContext('openEvent(1,fixture.events[0])',context);
assert.match(node('#modal-root').innerHTML,/<option value="1" selected>Билет куплен/);
console.log('Travel day, unknown transport icon, unchanged plane palette and ticket border states passed');

fixture.user.role='manager';vm.runInContext("view='schedule';render()",context);assert.doesNotMatch(node('#app').innerHTML,/data-act="nav" data-id="feedback"/);assert.match(node('#app').innerHTML,/data-act="send-feedback"/);
fixture.user.role='secretary';vm.runInContext('render()',context);assert.doesNotMatch(node('#app').innerHTML,/data-act="nav" data-id="feedback"/);
fixture.user.role='admin';vm.runInContext('render()',context);assert.match(node('#app').innerHTML,/data-act="nav" data-id="feedback"/);
vm.runInContext('openFeedback()',context);assert.match(node('#modal-root').innerHTML,/textarea name="message" required maxlength="5000"/);assert.match(node('#modal-root').innerHTML,/accept="image\/png,image\/jpeg,image\/webp"/);
vm.runInContext("feedbackRecords=[{id:1,kind:'bug',message:'<script>alert(1)</script>',status:'new',user_name:'User',username:'user',created_at:'2026-10-06 10:00:00',has_screenshot:1}];drawFeedback()",context);assert.doesNotMatch(node('#feedback-body').innerHTML,/<script>/);assert.match(node('#feedback-body').innerHTML,/&lt;script&gt;/);
vm.runInContext('openFeedbackDetail(1)',context);assert.match(node('#modal-root').innerHTML,/src="\/api\/feedback\/1\/screenshot"/);assert.match(node('#modal-root').innerHTML,/Отметить просмотренным/);
console.log('Feedback submission button, admin-only navigation, screenshot form and escaped message checks passed');

fixture.user.role='admin';fixture.employees[0].has_photo=true;vm.runInContext("view='schedule';render()",context);assert.match(node('#calendar').innerHTML,/class="employee-photo"/);assert.match(node('#calendar').innerHTML,/\/api\/employees\/1\/photo/);
vm.runInContext('openEmployee(1)',context);assert.match(node('#modal-root').innerHTML,/id="employee-photo-file"/);assert.match(node('#modal-root').innerHTML,/Убрать фотографию/);
vm.runInContext('openExport()',context);assert.match(node('#modal-root').innerHTML,/name="include_photos"/);assert.match(node('#modal-root').innerHTML,/Включить фотографии работников/);
fixture.user.role='manager';vm.runInContext('openEmployee(1)',context);assert.match(node('#modal-root').innerHTML,/employee-photo/);assert.doesNotMatch(node('#modal-root').innerHTML,/type="file"/);
console.log('Employee photo avatar, admin upload controls and optional PDF photo checkbox checks passed');
context.countryData=JSON.parse(fs.readFileSync('static/countries.json','utf8'));context.language='en';
vm.runInContext("countryCatalog=countryData;view='projects';fixture.projects[0].address='Example street 10';fixture.projects[0].country='LT';render()",context);
assert.match(node('#content').innerHTML,/Example street 10, Lithuania/);
assert.doesNotMatch(node('#content').innerHTML,/new-site|site-edit|Europe\/Stockholm/);
vm.runInContext('openProject()',context);
assert.match(node('#modal-root').innerHTML,/name="address"/);
assert.match(node('#modal-root').innerHTML,/list="project-countries"/);
assert.doesNotMatch(node('#modal-root').innerHTML,/name="site_id"|name="timezone"/);
assert.equal(vm.runInContext("countryCode('Lithuania')",context),'LT');
assert.equal(vm.runInContext("countryCode('Литва')",context),'LT');
assert.equal(vm.runInContext("countryCode('lt')",context),'LT');
assert.equal(vm.runInContext("countryCode('Atlantis')",context),'');
vm.runInContext('openEvent(1)',context);assert.doesNotMatch(node('#modal-root').innerHTML,/name="timezone"/);
console.log('Project-only form, location, searchable countries and timezone-free event form checks passed');

fixture.user.role='admin';vm.runInContext("view='schedule';render()",context);
assert.match(node('#app').innerHTML,/id="role-view"/);
node('#role-view').onchange({target:{value:'manager'}});
assert.equal(fixture.user.role,'admin');
assert.equal(vm.runInContext('effectiveRole()',context),'manager');
assert.match(node('#app').innerHTML,/id="role-view"/);
assert.doesNotMatch(node('#content').innerHTML,/data-act="new-user"|data-act="new-team"/);
assert.doesNotMatch(node('#app').innerHTML,/data-id="users"|data-id="feedback"/);
vm.runInContext("setRoleView('secretary')",context);
assert.doesNotMatch(node('#content').innerHTML,/data-palette="rest"|data-palette="vacation"/);
assert.match(node('#content').innerHTML,/data-palette="sick"/);
vm.runInContext('openTools(1)',context);
assert.doesNotMatch(node('#modal-root').innerHTML,/tool-cycle|tool-deactivate/);
vm.runInContext("view='users';render()",context);
assert.equal(vm.runInContext('view',context),'schedule');
vm.runInContext("setRoleView('admin')",context);
assert.match(node('#content').innerHTML,/data-act="new-user"|data-act="new-team"/);
fixture.user.role='manager';vm.runInContext('render()',context);
assert.doesNotMatch(node('#app').innerHTML,/id="role-view"/);
vm.runInContext("setRoleView('admin')",context);
assert.equal(vm.runInContext('effectiveRole()',context),'manager');
fixture.user.role='admin';vm.runInContext("setRoleView('invalid')",context);
assert.equal(vm.runInContext('effectiveRole()',context),'admin');
console.log('Admin view switch preserves account role, applies manager/secretary UI and rejects non-admin switching');

vm.runInContext('pickWorker(openCycle)',context);
assert.match(node('#modal-root').innerHTML,/id="plan-worker-search"/);
assert.match(node('#modal-root').innerHTML,/type="checkbox" name="employee_ids"/);
assert.doesNotMatch(node('#modal-root').innerHTML,/<select name="employee_id"/);
vm.runInContext('openCycle([1])',context);
assert.match(node('#modal-root').innerHTML,/name="work_weeks"/);
vm.runInContext("setRoleView('secretary');openPeriod([1])",context);
assert.match(node('#modal-root').innerHTML,/value="sick"/);
assert.doesNotMatch(node('#modal-root').innerHTML,/value="vacation"/);
vm.runInContext("setRoleView('admin')",context);
console.log('Planning supports searchable checkbox selection and group cycle/period forms');

fixture.user.role='admin';vm.runInContext("setRoleView('admin');openEmployee(1)",context);
assert.match(node('#modal-root').innerHTML,/data-act="delete-employee-card"/);
vm.runInContext("modalActions['delete-employee-card']()",context);
assert.match(node('#modal-root').innerHTML,/pattern="DELETE"/);
assert.match(node('#modal-root').innerHTML,/без возможности восстановления/);
fixture.user.role='manager';vm.runInContext('openEmployee(1)',context);
assert.doesNotMatch(node('#modal-root').innerHTML,/delete-employee-card/);
fixture.user.role='admin';
console.log('Permanent employee deletion requires admin and explicit DELETE confirmation');
